name: Run Unit Tests

on:
  workflow_call:

jobs:
  test:
    name: Execute Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set Up Python # Setting up python first just in case make test ever has python dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -e ".[dev]"

      - name: Run Make Test
        run: make test

      - name: Run Unit Tests
        run: make pytest
